name: Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup JDK 21
        uses: actions/setup-java@v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
      - name: Build with Gradle Wrapper
        run: ./gradlew build --build-cache --configuration-cache
      - name: Generate Kover HTML Report
        run: ./gradlew koverHtmlReport
      - name: Merge Artifacts
        run: |
          mkdir full pure
          find . -name "*.jar" -exec cp {} full \;
          rm full/buildSrc.jar full/gradle-wrapper.jar
          find full -name "*.jar" ! -name "*-sources.jar" ! -name "*-htmldoc.jar" ! -name "*-javadoc.jar" -exec cp {} pure \;
          for f in pure/*; do mv ${f} ${f%-*}.jar; done
          echo "Full:"
          cd full
          stat --printf '%n\t%s\n' *
          cd ..
          echo "Pure:"
          cd pure
          stat --printf '%n\t%s\n' *
          cd ..
      - name: Upload Full Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: "Full"
          path: full
      - name: Upload Pure Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: "Pure"
          path: pure
      - name: Merge Pages
        run: | 
          mkdir pages
          mv ./build/reports/kover/html/ ./pages/reports
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: "./pages"
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: publish to GitHub Pages
        uses: actions/deploy-pages@v4.0.0
