name: Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup JDK 21
        uses: actions/setup-java@v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
      - name: Build with Gradle Wrapper
        run: ./gradlew build check --build-cache --configuration-cache
      - name: Build Docs
        run: |
          ./gradlew dokkaGenerate
          mv ./build/dokka ./pages/docs
      - name: Generate Kover HTML Report
        run: ./gradlew koverHtmlReport
      - name: Merge Artifacts
        run: |
          mkdir full
          find . -name "*.jar" -exec cp {} full \;
          rm full/buildSrc.jar full/gradle-wrapper.jar full/kover-jvm-agent.jar
          find full -name "*.jar" ! -name "*-sources.jar" ! -name "*-htmldoc.jar" ! -name "*-javadoc.jar" -exec cp {} pages/jars/ \;
          for f in pages/jars/*; do mv ${f} ${f%-*}.jar; done
          echo "Full:"
          cd full
          stat --printf '%n\t%s\n' *
          cd -
          echo "Pure:"
          cd pages/jars
          stat --printf '%n\t%s\n' *
          cd -
      - name: Upload Full Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: "Full"
          path: full
      - name: Upload Pure Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: "Pure"
          path: pages/jars
      - name: Generate Download Page
        run: |
          cd pages/jars
          list=$(ls -l *.jar | awk '{print "        <tr><td>"$9"</td><td>"$5"</td><td></td></tr>"}' | tr '\n' '\\n')
          sed -i 's@<$list template$>@'"$list"'@g' pages/download.html
      - name: Merge Pages
        run: | 
          mkdir ./pages/test/
          mv ./build/reports/kover/html/ ./pages/test/coverage
          mv ./build/reports/tests/test/aggregated-results ./pages/test/result
          ls -alF ./pages/jars/
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: "./pages"
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: publish to GitHub Pages
        uses: actions/deploy-pages@v4.0.0
